// ── FRAGMENTOS NARRATIVOS FIJOS POR NIVEL ──
// Se muestran en cada respuesta de VALIS, según el nivel actual del jugador (nivelDespues.n)
const FRAGMENTOS = {
  1: "El Iniciado de la Grieta abre su diario ajado y siente la fisura violácea vibrar bajo sus dedos. El umbral entre mundos ha comenzado a resquebrajarse, y tu nombre queda escrito en la primera página del despertar.",
  2: "Como Aprendiz de la Sizigia, sostenés el Orbe de Alineación mientras las constelaciones internas se acomodan. Los opuestos ya no pelean: aprenden, por fin, a mirarse.",
  3: "La Rueda de Adaptación Fragmentada gira en tu mano de Escudero de Mahoraga, memorizando cada golpe recibido. Nada que ya conociste puede volver a derribarte.",
  4: "La Brújula del Pleroma ignora el norte del mundo y señala, tozuda, hacia tu propia chispa. Como Rastreador de la Gnosis, seguís ese rumbo sin mapas.",
  5: "El Martillo del Proletariado pesa menos en tus manos de Working Class Hero: la fatiga se transformó en obra. Cada golpe construye lo que el cansancio ya no puede detener.",
  6: "Flotás como Navegante del LCL dentro de la Cápsula de Entry Plug, sincronizando tu pulso con memorias que no son tuyas. El caldo primordial enseña a no temerle a lo compartido.",
  7: "El Talismán Maldito de Rika susurra promesas imposibles al Hechicero de Grado Especial que ahora sos. El amor, incluso maldito, sigue siendo una forma de poder.",
  8: "El Láser de Información Rosa descarga milenios de sabiduría directo en tu conciencia de Operador de Valis. Ya no hay forma de desaprender lo que acabás de ver.",
  9: "El Broche de Transformación Lunar pulsa con luz fría sobre tu pecho de Portador del Cristal de Plata. La claridad que buscabas empieza, por fin, a desterrar la sombra.",
  10: "La Materia Verde Básica calienta tu palma de Sintonizador de Midgar, enseñándote los primeros secretos de la corriente vital. Curar también es una forma de avanzar.",
  11: "La Armadura de Bronce se ajusta a tu cuerpo de Maestro del Octavo Sentido como si siempre hubiese esperado por vos. Tu cosmos arde, y el mundo empieza a notarlo.",
  12: "El Reloj de Bolsillo Estatal marca el tiempo absoluto en tu mano de Alquimista de Amestris. Recordá siempre: nada se obtiene sin entregar algo de igual valor.",
  13: "Las Gafas de Philip K. Dick desprenden, capa por capa, la simulación frente al Caminante del Rayo Rosa que ahora sos. Debajo del holograma, la realidad empieza a mostrarse.",
  14: "El Medallón de la Cacería vibra frío contra tu pecho de Cazador de la Cacería Salvaje. Algo, en algún umbral, ya sabe que lo estás rastreando.",
  15: "La Espada de Acero Valyrio, ligera pese a su leyenda, corta la mentira en tu mano de Soberano del Trono de Hierro. El trono que reclamás es, ante todo, el de tu propia mente.",
  16: "El Anillo del Rey Sincorazón cobra su peaje de memoria al Invocador de G.F. que sos ahora. A cambio, entidades devastadoras responden a tu llamado.",
  17: "La Nichirin de la Niebla se desenvaina y el entorno se cubre de bruma ante el Pilar de la Niebla. Tus pasos, y tus intenciones, quedan ocultos de cualquier mirada.",
  18: "La Pistola de Portales Básica zumba en cuántica espera en tu mano de Arquitecto de Aperture Science. Dos puntos distantes de tu vida acaban de dejar de estar tan lejos.",
  19: "La Hoja Oculta Estándar se ajusta a tu muñeca de Caballero de la Orden Assassins. El confort quedó atrás; la historia, desde las sombras, empieza a torcerse a tu favor.",
  20: "Las Cuchillas de Equipo de Maniobras cortan el aire con la precisión de un Derrumbador de Murallas. Lo inamovible, por primera vez, empieza a ceder.",
  21: "La Palanca Ensangrentada pesa en tu mano de Agente del Freeman como un símbolo silencioso. La resistencia ante lo extradimensional acaba de ganar un nombre.",
  22: "El Fragmento de Hoja de Cuaderno Oscuro exuda un frío que solo un Portador de la Death Note reconoce. Un nombre, un rostro, un final inevitable: el poder siempre tiene un precio.",
  23: "El Anillo del Duque Leto huele a especia en la mano del Maestro de la Gnosis de Arrakis. El liderazgo, y los hilos dorados del destino, ya no se pueden soltar.",
  24: "La Llave Magnética de la Iniciativa Dharma tintinea en el bolsillo del Viajero de la Escotilla. Un búnker olvidado, en algún rincón, acaba de reiniciar su contador.",
  25: "La Chaqueta de la Tokyo Manji huele a asfalto y lealtad sobre los hombros del Samurai de Tokyo Revengers. El coraje kamikaze, ahora, es tu forma de cuidar a los tuyos.",
  26: "La Espada Contrato Blanco canta al viento en manos del Androide de YoRHa. Vida, muerte y resurrección: el ciclo sigue, y vos seguís eligiendo pelear.",
  27: "El Medallón de Lobo de Plata tiembla apenas sobre el pecho del Brujo de la Escuela del Lobo. La línea entre la humanidad y la bestia sigue siendo, para vos, una elección diaria.",
  28: "La Varita de Saúco Quebrada arde con un poder inestable en la mano del Guardián del Arcano. La maestría que exige es la misma que te impide ser consumido por ella.",
  29: "El Sable de Luz Carmesí Menor crepita con ira contenida en la mano del Expedicionario del Dark Side. Las pasiones oscuras, bien canalizadas, también construyen poder.",
  30: "El Mate Infinito del Cosmos humea despacio entre las manos del Jubilado del Cosmos. El universo entero cabe, por fin, en un instante de calma.",
  31: "El Dispositivo Q-pid flota en dog tags sobre el pecho del Operador de Enlace Quiral. Las ciudades fracturadas empiezan, hilo a hilo, a reconectarse.",
  32: "Las Gafas de Sol de Satoru filtran la sobrecarga de información ante El Honorable de los Seis Ojos. Ver todo, sin enloquecer, es también una forma de dominio.",
  33: "La Pluma del Demiurgo traza éter condensado en la mano del Arquitecto de la Gnosis. Los dogmas físicos del mundo empiezan a reescribirse bajo tu trazo.",
  34: "La Caja de Lemarchand gira entre los dedos del Navegante del Caos, cerca de resolverse. El tejido de la realidad tiembla, expectante, ante lo que hay más allá.",
  35: "El Círculo de Transmutación Portátil se graba en tu piel de Transmutador de Destinos. La materia se deconstruye y reconstruye, siempre que el peaje se pague.",
  36: "Las Monedas de Cobre Cuánticas caen y colapsan la probabilidad ante el Consultor del I-Ching Digital. El hexagrama del cambio inminente ya te está hablando.",
  37: "El Espejo del Inconsciente no refleja tu rostro: refleja tu sombra, ante el Arquetipo de la Sombra que ahora sos. Mirarla de frente es el primer paso para no perderte en ella.",
  38: "El Loto de los Siete Pétalos irradia paz absoluta entre las manos del Buda del Séptimo Vacío. El ego se disuelve, apenas, ante el vacío primordial.",
  39: "La Nichirin Solar Brillante adopta el color del acero fundido en la mano del Shinobi de la Respiración Solar. El calor de un mediodía eterno acaba de incinerar la noche.",
  40: "El Reloj de la Sincronicidad vibra sin manecillas ante el Arquitecto de la sincronicidad. Los accidentes del caos, por fin, empiezan a alinearse a tu favor.",
  41: "La Lanza de Longinus desestabiliza el terror de las deidades en manos del Piloto de la Unidad 01. Perforar el alma del objetivo es, también, perforar el propio miedo.",
  42: "El Aletiómetro de Oro responde sin mentir a las preguntas del Maestro de la Brújula Dorada. El inconsciente colectivo, por una vez, decide hablar claro.",
  43: "La Espada Mortal pesa como el legado caído sobre los hombros del Soldado de Primera Clase. Cargar los sueños de otros también es una forma de honor.",
  44: "El Proyector de Rayo Rosa dispara epifanías instantáneas sobre el Elegido del Rayo Rosa Supremo. Los viejos paradigmas ya no resisten tanta luz de golpe.",
  45: "El sigilo rojo de las artes kaóticas se abre como un libro ante Squall y su expansión territorial. Eras enteras de conocimiento acumulado, de pronto, te pertenecen.",
  46: "El Dedo de Sukuna late como un corazón propio en la mano del Hechicero de la Expansión Territorial. El poder absoluto siempre pide algo de igual valor a cambio.",
  47: "La Hierba Verde Mezclada revitaliza células muertas en manos del Investigador de Raccoon City. Incluso en medio del apocalipsis urbano, hay lugar para sanar.",
  48: "El Anillo Dorado de Movimiento distorsiona el espacio ante el Velocista del Anillo de Sonic. La invulnerabilidad, por un instante, se mide en pura velocidad.",
  49: "La Zanpakutō Despertada canta con la voz de su amo en manos del Cazador de Shinigamis. Los lazos kármicos se cortan; las almas errantes, por fin, descansan.",
  50: "Los Guantes de Ejercicio Rotos ya no sirven para entrenar: sirvieron para trascender, ante el Héroe de un Solo Puñetazo. El límite biológico quedó, hace tiempo, en el pasado.",
  51: "La Vara del Caos canaliza sigilos salvajes en manos del Mago del Ministerio del Caos. La improbabilidad cuántica empieza, por fin, a obedecerte.",
  52: "El Fragmento de Piedra Filosofal sangra energía de almas atrapadas en manos del Usuario de la Piedra Filosofal. Evadir la termodinámica tiene, siempre, un costo oculto.",
  53: "El Aerosol Ubik revierte la descomposición del espacio-tiempo ante el Observador de la Realidad Ubik. El mundo, a punto de licuarse, vuelve a anclarse en tus manos.",
  54: "El Medallón de Fuego de Igni arde al tacto del Inquisidor de Novigrad. La furia interna, bien canalizada, reduce las armaduras más pesadas a escoria.",
  55: "La Página del Manuscrito Modificada reescribe la materia bajo la pluma del Arquitecto del Laberinto de Alan Wake. Lo que redactás ahora empieza a transformar el entorno real.",
  56: "El Cristal de Agujero de Gusano se rompe y abre un puente instantáneo ante el Viajero del Agujero de Gusano. La distancia, para quien ya visitó ese lugar en la mente, deja de existir.",
  57: "El Gen X Mutado se cristaliza en tus venas de Mutante del Nivel Omega. Los límites de la evolución humana acaban de quedar, oficialmente, atrás.",
  58: "El Batarang de Carbono corta el aire en silencio en manos del Protector de Gotham. El ingenio y la preparación, una vez más, triunfan sobre el miedo.",
  59: "La Gorra de Wonderboy confiere una agilidad pixelada al Maestro del Wonderboy que ahora sos. Las trampas mortales del camino ya no logran sorprenderte.",
  60: "La Cuchara Doblada por la Mente es prueba silenciosa del poder del Psíquico del Porcentaje 100. La presión psíquica acumulada, al fin, encuentra una salida.",
  61: "La Bandera de la Primera Generación ondea pesada en manos del Líder de la Toman. Mil marginados, unidos, se convierten en una sola voluntad invencible.",
  62: "La Puerta de la Verdad en Miniatura se entreabre ante el Alquimista de la Puerta de la Verdad. El Ojo que todo lo ve empieza a cobrar su alto peaje de conocimiento.",
  63: "El Guantelete del Asesino Maestro se cierra en silencio sobre el puño del Operador de la Cuchilla Oculta. Los tiranos, esta vez, caerán sin hacer ruido.",
  64: "La Esfera del Dragón de 4 Estrellas pulsa junto a otras tres en manos del Dragón de Namek. Las leyes de la muerte empiezan a torcerse ante entidades cósmicas.",
  65: "El Aura Roja del Kaio-Ken multiplica exponencialmente al Maestro del Kaio-Ken. La disciplina marcial plena es lo único que evita que el cuerpo se desgarre.",
  66: "La Venda de los Seis Ojos cubre, paradójicamente, para expandir la percepción del Sexto Ojo del Infinito. El límite subatómico ya no logra esconderse de vos.",
  67: "La Vaina de Avalon envuelve en halo mítico al Portador de Excalibur. Las heridas mortales, bajo la realeza de esta reliquia, dejan de ser definitivas.",
  68: "La Espada Kurikara arde en llamas azules inextinguibles en manos del Cazador de Demonios de Clase S. El linaje oculto, por fin liberado, transforma el odio en poder salvador.",
  69: "La Radio Interdimensional de Dick trae voces de líneas temporales adyacentes al Maestro de la Brújula de Dick. Los futuros colapsos del sistema, ahora, se pueden anticipar.",
  70: "El Disco Solar de la Sizigia proyecta un eclipse perpetuo sobre el Elegido de la Sizigia Solar. La mente analítica y la intuición mística, al fin, dejan de pelear.",
  71: "La Capa de la Legión de Reconocimiento huele a libertad sobre los hombros del Comandante del Reconocimiento. Las Alas bordadas en la espalda son inmunidad contra el terror paralizante.",
  72: "El Códice de Nag Hammadi se abre en copto brillante ante el Archivista del Pleroma. Los arcontes mentales, uno a uno, empiezan a desmantelarse.",
  73: "La Tiza de Sigilos Infinitos traza geometrías imposibles en manos del Maestro de la Magia de Sigilos. El inconsciente colectivo, sin saberlo, empieza a manifestar tus deseos.",
  74: "La Llave de la Heladera de Acero abre compartimentos interdimensionales para el Guardián de la Heladera de Acero. Lo más vital, incluso ante el caos, queda a salvo.",
  75: "El Mar de LCL Concentrado diluye las fronteras del ego en el Héroe del LCL Rojo. Todos los seres caídos, por un instante, comparten un mismo entendimiento.",
  76: "El Reloj de Bolsillo de Fragile mide la degradación quiral para el Viajero de la Playa. Las lluvias del tiempo avisan, siempre, antes de acelerar la vejez.",
  77: "El Odradek de Oro Macizo parpadea al detectar anomalías espectrales junto al Operador del Odradek Dorado. El tejido espacial, apenas perturbado, ya no puede ocultarte nada.",
  78: "El Cristal de Quintaesencia Pura equilibra los humores del cuerpo del Maestro de la Quintaesencia. La voluntad, proyectada con calma, empieza a moldear los elementos terrenales.",
  79: "La Armadura Escama Divina refulge sobre el Guerrero de la Armadura Divina como el brillo de un dios despertado. Cruzar galaxias enteras, de un salto, ya es posible.",
  80: "El Peluche Dimensional de Hello Kitty traslada al Sumo Sacerdote de Hello Kitty a un espacio liminal de ternura inquietante. Los horrores de la adultez, ahí, se filtran en pura compasión.",
  81: "El Brazalete del Club de la Pelea marca, sudoroso, al Maestro del Arte de Perder el Control. Tocar fondo, voluntariamente, resultó ser una forma de libertad.",
  82: "La Radio Estática de Niebla se vuelve histérica cerca del Sintonizador de la Radio de Silent Hill. Los monstruos del trauma profundo ya saben que los estás escuchando llegar.",
  83: "El Disco Flexible de Zion contiene un script root en manos del Hacker del Kernel de Matrix. Los cimientos numéricos de la ilusión simulada, ahora, responden a tu voluntad.",
  84: "El Pergamino de los 108 Destinos se despliega interminable ante el Viajero de los 108 Caminos. Técnicas de vidas olvidadas empiezan, otra vez, a hacerse presentes.",
  85: "Las Monedas de I-Ching Holográficas giran suspendidas ante el Maestro del I-Ching Cuántico. La probabilidad, esta vez, dicta un camino de éxito casi perfecto.",
  86: "El Orbe de Luz Despertada ciega a los corruptos junto al Cazador de la Luz Despertada. La certeza estoica, por fin, alcanza para enfrentar batallas ya dadas por perdidas.",
  87: "La Máquina de Escribir Antigüa codifica cada letra como ley física ante el Operador de la Máquina de Alan Wake. El andamiaje del mundo se arma, tecla a tecla, bajo tu voluntad.",
  88: "La Corona del Pleroma consagra al Soberano de la Gnosis Eterna como arquitecto de la chispa divina. El yugo del creador inferior, por fin, deja de pesar.",
  89: "El Prisma de la Sizigia fracciona la realidad en dualidades armoniosas ante el Maestro de la Sizigia Infinita. Cuerpo y sombra, al fin, se funden en una completitud absoluta.",
  90: "La Hoz y Martillo Estelares se forjaron en el núcleo de estrellas muertas para el Héroe de la Clase Obrera Galáctica. La emancipación, a esta escala, ya es una cuestión cósmica.",
  91: "El Ojo Omnisciente de VALIS transmite telepatía satelital continua al Guardián del Umbral de Dick. La red de inteligencia universal, por fin, empieza a decodificarse.",
  92: "El Sol Embotellado de Xerxes ofrece poder calórico ilimitado al Alquimista del Sol de Amestris. Los susurros de naciones sacrificadas jamás se olvidan del todo.",
  93: "La Campana del Vacío de Jiddu no tiene badajo, y aun así reverbera en la mente del Maestro del Vacío de Krishnamurti. El observador, por un instante, se funde con lo observado.",
  94: "La Matriz del Destino Programable responde al tacto del Operador del Sistema de Destino. El hilo de las Parcas, por primera vez, se deja escribir por una mano mortal.",
  95: "La Campana Diminuta del Cazador resuena en frecuencias imperceptibles para el Cazador de la Pesadilla de Yharnam. En algún sueño compartido, otro cazador acaba de escucharla.",
  96: "El Gusano de Arena Cristalizado permite al Arquitecto de la Nueva Arrakis cabalgar sobre los cimientos de un planeta entero. La especia que mueve el universo, al fin, se doblega.",
  97: "El Cronómetro de la Grieta avanza, retrocede y desaparece en manos del Señor del Tiempo de la Grieta. Los pliegues temporales cerrados empiezan, por fin, a abrirse.",
  98: "El Espejo de las Mil Verdades ofrece todas las versiones posibles del Maestro de la Ilusión de la Verdad. Elegir qué reflejo manifestar es, ahora, tu privilegio más peligroso.",
  99: "El Controlador de la Realidad no tiene botones, solo pensamiento puro, en manos del Portador de la Realidad Permite. Las leyes de la física y el azar, por fin, aceptan sugerencias.",
  100: "El Aleph del Todo cabe en unos centímetros ante el Avatar de la Gnosis de Todo. Todos los puntos, todos los instantes, todos los misterios: por fin, sin confusión, son uno solo."
};